[build]
  command = "npm install && npm run build"  # æˆ– "yarn install"
  publish = "."       

[functions]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
