[build]
  command = "npm install"  # 或 "yarn install"
  publish = "public"       # 静态文件目录

[functions]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index1.html"
  status = 200